"""empty message

Revision ID: 091aadb441f2
Revises: bb8148e0f96e
Create Date: 2017-03-08 22:54:42.882000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091aadb441f2'
down_revision = 'bb8148e0f96e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special', sa.Column('photo', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special', 'photo')
    ### end Alembic commands ###
