"""empty message

Revision ID: 1978f39ac273
Revises: 9b13eb436607
Create Date: 2017-02-27 16:37:14.552000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1978f39ac273'
down_revision = '9b13eb436607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('buy_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('excellent', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('hot_goods', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('integral', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('limit_end_time_price', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('limit_start_time_price', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('new_goods', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('promote_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('sort', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('vip_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('products', 'limit_time_price')
    op.add_column('products_thumbnail', sa.Column('thumbnail_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_thumbnail', 'thumbnail_status')
    op.add_column('products', sa.Column('limit_time_price', mysql.DATETIME(), nullable=True))
    op.drop_column('products', 'vip_price')
    op.drop_column('products', 'view_count')
    op.drop_column('products', 'sort')
    op.drop_column('products', 'promote_price')
    op.drop_column('products', 'new_goods')
    op.drop_column('products', 'limit_start_time_price')
    op.drop_column('products', 'limit_end_time_price')
    op.drop_column('products', 'integral')
    op.drop_column('products', 'hot_goods')
    op.drop_column('products', 'excellent')
    op.drop_column('products', 'buy_count')
    # ### end Alembic commands ###
