"""empty message

Revision ID: 1c59c1d4f425
Revises: 1978f39ac273
Create Date: 2017-02-27 16:40:46.250000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c59c1d4f425'
down_revision = '1978f39ac273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_md5', sa.String(length=16), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('special_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vip_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Unicode(length=1000), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('combination', sa.String(length=255), nullable=True),
    sa.Column('products_id', sa.String(length=255), nullable=True),
    sa.Column('products_name', sa.String(length=255), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=True),
    sa.Column('goodpost', sa.Integer(), nullable=True),
    sa.Column('badpost', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('attribute', sa.Integer(), nullable=True),
    sa.Column('excellent', sa.Integer(), nullable=True),
    sa.Column('new_goods', sa.Integer(), nullable=True),
    sa.Column('hot_goods', sa.Integer(), nullable=True),
    sa.Column('limit_start_time_price', sa.DateTime(), nullable=True),
    sa.Column('limit_end_time_price', sa.DateTime(), nullable=True),
    sa.Column('promote_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('integral', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('buy_count', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_id_md5'), 'goods', ['id_md5'], unique=True)
    op.create_index(op.f('ix_goods_seller_id'), 'goods', ['seller_id'], unique=False)
    op.create_table('goods_thumbnail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('products_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'products', sa.Column('limit_time_price', sa.DateTime(), nullable=True))
    op.drop_column(u'products', 'sort')
    op.drop_column(u'products', 'view_count')
    op.drop_column(u'products', 'hot_goods')
    op.drop_column(u'products', 'new_goods')
    op.drop_column(u'products', 'integral')
    op.drop_column(u'products', 'buy_count')
    op.drop_column(u'products', 'vip_price')
    op.drop_column(u'products', 'limit_start_time_price')
    op.drop_column(u'products', 'excellent')
    op.drop_column(u'products', 'promote_price')
    op.drop_column(u'products', 'limit_end_time_price')
    op.drop_column(u'products_thumbnail', 'thumbnail_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'products_thumbnail', sa.Column('thumbnail_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'products', sa.Column('limit_end_time_price', mysql.DATETIME(), nullable=True))
    op.add_column(u'products', sa.Column('promote_price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column(u'products', sa.Column('excellent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'products', sa.Column('limit_start_time_price', mysql.DATETIME(), nullable=True))
    op.add_column(u'products', sa.Column('vip_price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column(u'products', sa.Column('buy_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'products', sa.Column('integral', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'products', sa.Column('new_goods', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'products', sa.Column('hot_goods', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'products', sa.Column('view_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'products', sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column(u'products', 'limit_time_price')
    op.drop_table('goods_thumbnail')
    op.drop_index(op.f('ix_goods_seller_id'), table_name='goods')
    op.drop_index(op.f('ix_goods_id_md5'), table_name='goods')
    op.drop_table('goods')
    # ### end Alembic commands ###
