"""empty message

Revision ID: 1d8306ad6038
Revises: 091aadb441f2
Create Date: 2017-03-09 17:57:56.530000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8306ad6038'
down_revision = '091aadb441f2'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('special', sa.Column('sort', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special', 'sort')
    ### end Alembic commands ###
