"""empty message

Revision ID: 455396a7c1d8
Revises: b91a40a6c187
Create Date: 2017-02-28 12:45:53.709000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '455396a7c1d8'
down_revision = 'b91a40a6c187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('goods_id', sa.Integer(), nullable=True))
    op.drop_column('order_products', 'products_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('products_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('order_products', 'goods_id')
    # ### end Alembic commands ###
