"""empty message

Revision ID: 4c70fbd0ab42
Revises: b23da830ae4d
Create Date: 2017-02-21 23:53:02.292000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c70fbd0ab42'
down_revision = 'b23da830ae4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_md5', sa.String(length=16), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('special_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('note', sa.Unicode(length=1000), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('combination', sa.String(length=255), nullable=True),
    sa.Column('products_id', sa.String(length=255), nullable=True),
    sa.Column('products_name', sa.String(length=255), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=True),
    sa.Column('goodpost', sa.Integer(), nullable=True),
    sa.Column('badpost', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id_md5'), 'products', ['id_md5'], unique=True)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_id_md5'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
