"""empty message

Revision ID: 61d5475f17b7
Revises: c75ea6b3d9d6
Create Date: 2017-02-21 22:39:35.896000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61d5475f17b7'
down_revision = 'c75ea6b3d9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('products', sa.Column('special_price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.drop_column('products', 'Original_price')
    op.drop_column('products', 'Special_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Special_price', mysql.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('products', sa.Column('Original_price', mysql.DECIMAL(precision=15, scale=2), nullable=True))
    op.drop_column('products', 'special_price')
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###
