"""empty message

Revision ID: 6573cd6e099a
Revises: 9379017eeb69
Create Date: 2017-02-28 22:28:01.857000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6573cd6e099a'
down_revision = '9379017eeb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_goods', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_goods', 'count')
    # ### end Alembic commands ###
