"""empty message

Revision ID: 9379017eeb69
Revises: f55d2bf7a079
Create Date: 2017-02-28 20:41:46.805000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9379017eeb69'
down_revision = 'f55d2bf7a079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_goods')
    # ### end Alembic commands ###
