"""empty message

Revision ID: 9b13eb436607
Revises: 4d412627c132
Create Date: 2017-02-24 13:46:03.004000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b13eb436607'
down_revision = '4d412627c132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('special_id', sa.Integer(), nullable=True),
    sa.Column('products_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'category', sa.Column('ico', sa.String(length=255), nullable=True))
    op.add_column(u'category', sa.Column('sort', sa.Integer(), nullable=True))
    op.add_column(u'category', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'category', 'status')
    op.drop_column(u'category', 'sort')
    op.drop_column(u'category', 'ico')
    op.drop_table('special_products')
    op.drop_table('special')
    # ### end Alembic commands ###
