"""empty message

Revision ID: b23da830ae4d
Revises: e88a2d313799
Create Date: 2017-02-21 23:02:23.115000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23da830ae4d'
down_revision = 'e88a2d313799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_seller_id', table_name='products')
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.add_column('products_thumbnail', sa.Column('seller_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_thumbnail', 'seller_id')
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.create_index('ix_products_seller_id', 'products', ['seller_id'], unique=True)
    # ### end Alembic commands ###
