"""empty message

Revision ID: bb8148e0f96e
Revises: 2801ab5d8573
Create Date: 2017-03-03 14:54:12.030000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8148e0f96e'
down_revision = '2801ab5d8573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('unit', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'unit')
    # ### end Alembic commands ###
