"""empty message

Revision ID: c214e66cf248
Revises: c60506c21f3e
Create Date: 2017-02-20 15:32:22.022000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c214e66cf248'
down_revision = 'c60506c21f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupons')
    op.add_column('products', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('sellers', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'status')
    op.drop_column('products', 'status')
    op.create_table('coupons',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('discount', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('receive_time', mysql.DATETIME(), nullable=True),
    sa.Column('use_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('seller_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('top_price', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('discount_price', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('coupon_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
