"""empty message

Revision ID: c60506c21f3e
Revises: d5697882e3bf
Create Date: 2017-02-20 13:54:46.270000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60506c21f3e'
down_revision = 'd5697882e3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'create_time')
    # ### end Alembic commands ###
