"""empty message

Revision ID: c8ea2b66e4e8
Revises: 1c59c1d4f425
Create Date: 2017-02-27 16:49:35.177000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8ea2b66e4e8'
down_revision = '1c59c1d4f425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('goods_id', sa.String(length=255), nullable=True))
    op.add_column('goods', sa.Column('goods_name', sa.String(length=255), nullable=True))
    op.drop_column('goods', 'products_name')
    op.drop_column('goods', 'products_id')
    op.add_column('goods_thumbnail', sa.Column('goods_id', sa.Integer(), nullable=True))
    op.drop_column('goods_thumbnail', 'products_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_thumbnail', sa.Column('products_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('goods_thumbnail', 'goods_id')
    op.add_column('goods', sa.Column('products_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('goods', sa.Column('products_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('goods', 'goods_name')
    op.drop_column('goods', 'goods_id')
    # ### end Alembic commands ###
