"""empty message

Revision ID: cd7f7789ee73
Revises: feb2a45d4aa7
Create Date: 2017-02-24 10:52:18.615000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7f7789ee73'
down_revision = 'feb2a45d4aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('products', sa.Integer(), nullable=True),
    sa.Column('ean', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'products', sa.Column('limit_time_price', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'products', 'limit_time_price')
    op.drop_table('ean')
    # ### end Alembic commands ###
