"""empty message

Revision ID: d5697882e3bf
Revises: 9c69db5b89eb
Create Date: 2017-02-20 13:43:01.279000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5697882e3bf'
down_revision = '9c69db5b89eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('category', 'seller_id')
    # ### end Alembic commands ###
