"""empty message

Revision ID: e88a2d313799
Revises: 28ac9e69f6fa
Create Date: 2017-02-21 22:55:32.728000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88a2d313799'
down_revision = '28ac9e69f6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.Numeric(), nullable=True))
    op.add_column('products', sa.Column('special_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'special_price')
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###
