"""empty message

Revision ID: f55d2bf7a079
Revises: 455396a7c1d8
Create Date: 2017-02-28 12:52:51.574000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f55d2bf7a079'
down_revision = '455396a7c1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_products',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('order_goods')
    # ### end Alembic commands ###
