"""empty message

Revision ID: feb2a45d4aa7
Revises: 13733be3ea4f
Create Date: 2017-02-22 22:38:57.537000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb2a45d4aa7'
down_revision = '13733be3ea4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('attribute', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('tag', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('thumbnail', sa.String(length=255), nullable=True))
    op.drop_index('ix_sellers_order_seller_id', table_name='sellers_order')
    op.create_index(op.f('ix_sellers_order_seller_id'), 'sellers_order', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_order_seller_id'), table_name='sellers_order')
    op.create_index('ix_sellers_order_seller_id', 'sellers_order', ['seller_id'], unique=True)
    op.drop_column('products', 'thumbnail')
    op.drop_column('products', 'tag')
    op.drop_column('products', 'attribute')
    # ### end Alembic commands ###
